# ---------------* Basic *---------------
auto_reconnect = false

# --------------* Discord *--------------
discord_user_token = ""
discord_web_socket = "wss://gateway.discord.gg/?v=10&encording=json"

# ----------------* Log *----------------
# save log as a text file
save_log = true

# console log with color
log_with_colors = true

# include the current time zone into the log
log_with_time_zone = false

display_server_id = false
display_channel_id = false
display_user_id = false

# ----------------* Filter *---------------
enable_server_whitelist = false
enable_channel_whitelist = false
whitelist_sever = [
    "server_id",
]
whitelist_channel = [
    "channel_id",
]

enable_server_blacklist = false
enable_channel_blacklist = false
blacklist_sever = [
    "server_id",
]
blacklist_channel = [
    "channel_id",
]


